### PR TITLE
Audiodef hydrogen

### PR DESCRIPTION
**Pull request by audiodef**
Notes:
1. Had to redo src_configure
2. Added media-libs/raptor as dependency. media-libs/raptor was itself modified to perform dosyms for raptor.h and raptor2.h, otherwise, hydrogen cannot find these files
3. Added "extra" use flag to pull in drumkits

### CODE REVIEW

**Comment by simonvanderveldt** [comment]
@audiodef Any particular reason you want to add these to the overlay?
They already exist upstream, see https://github.com/gentoo/gentoo/tree/master/media-libs/raptor and https://github.com/gentoo/gentoo/tree/master/media-sound/hydrogen.
raptor is the same version, so I don't think there's anything to do there
hydrogen is an older version, so a bump upstream would be nice

**Comment by audiodef** [comment]
Yes, I want to add it here because I also needed to update hydrogen-drumkits and raptor. I don't think I can get my modification to the raptor ebuild pushed upstream - just a feeling. I needed to add a couple of dosyms to raptor or the latest hydrogen will not build. It's asking a lot and at best I think it will take a long time to make it upstream, if at all.

**Comment by simonvanderveldt** [comment]
@audiodef I'd like to move this forward, it's our oldest PR :)
What needs to be done to get this upstream? Do you have a list of items/bug reports?

There's a bump request/bug here https://bugs.gentoo.org/570814 which already includes an updated ebuild, though i haven't check it's quality. We can check it and create a PR to the gentoo tree to update it.

Regarding the rapor issues, it seems like those have been fixed by https://github.com/hydrogen-music/hydrogen/pull/508. I've asked there to verify. If it fixes the issues we can create a patch for Hydrogen 0.9.7 with those changes in it.

**Comment by simonvanderveldt** [comment]
FYI a live ebuild for Hydrogen was just added to the gentoo tree https://bugs.gentoo.org/570814#c21

**Comment by audiodef** [comment]
Very nice. :-)
      
      On 01/01/2018 06:38 AM, Simon van der Veldt wrote:
    
    
      FYI a live ebuild for Hydrogen was just added to the gentoo
        tree https://bugs.gentoo.org/570814#c21
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/gentoo-audio/audio-overlay","title":"gentoo-audio/audio-overlay","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/gentoo-audio/audio-overlay"}},"updates":{"snippets":[{"icon":"PERSON","message":"@simonvanderveldt in #68: FYI a live ebuild for Hydrogen was just added to the gentoo tree https://bugs.gentoo.org/570814#c21"}],"action":{"name":"View Pull Request","url":"https://github.com/gentoo-audio/audio-overlay/pull/68#issuecomment-354648957"}}}

**Comment by simonvanderveldt** [comment]
I think the majority of the issues with Hydrogen have been fixed upstream/in the gentoo tree, with a snapshot (added here https://github.com/gentoo/gentoo/commit/47ebefac39bde969dd959d74604fe09c729d64d2#diff-d8d033582037b2542d7859e7617d4ab2) being stabilized. Going to close this issue, if there's anything left we need to do feel free to create a new one :)

**Pull request closed without merging**
