### PR TITLE
media-sound/ladish: move to fork with python 3 compat

### PR DESCRIPTION
**Pull request by maxaudron**
I spent the weekend pulling ladish away from using waf to meson and
converting everything to python 3 as needed. The fork does not install
laditools I'd put that into a separate ebuild soon.

I'm having some smaller issues in conjunction with cadence right now
and it's not autostarting ladishd, don't know exactly why yet butt I think
it's more related to cadence.

And for the future I'm planning to bring back the GUI and potentially
 rewrite ladish_control in C to get rid of the python dep

### CODE REVIEW

**Comment by simonvanderveldt** [comment]
Thanks for the PR. Did you discuss this with nedko? He's pretty active at the #lad IRC. I pointed him at the openSUSE patches for Python3 (https://build.opensuse.org/package/show/multimedia:apps/ladish) just this week which he would look into.
I have most of those patches applied to the ebuild locally as well, but would prefer it to be fixed upstream and pull those commits in as patches.

**Comment by maxaudron** [comment]
I talked to nedko and he is interest, but I'll have to clean up my stuff first, I'll update the build to the new upstream then.

**Comment by simonvanderveldt** [comment]
FYI I've just merged some changes to make both ladish-1 as well as ladish-9999 work with Python 3, all of this still uses waf to build and the new upstream git repo from nedko. I didn't really want to switch to a third party repo, especially now that most of your changes have been merged into nedko's repo. He also said he expects to create a new release in March, if/when that happens we can look at switching to using meson, although I don't think he uses it himself, so it might not get the same level of attention as the waf build?

**Comment by maxaudron** [comment]
Sorry, kinda fell off my table, I've had the ebuild lying around for a bit already. 

Gladish works fine with this too, and I've been using it for a bit, there are some parts that open to laditools which right now isn't working in py3 quite yet, but it's not much of a hard dependency, so I think it's ok.

**Comment by simonvanderveldt** [comment]
> Gladish works fine with this too, and I've been using it for a bit, there are some parts that open to laditools which right now isn't working in py3 quite yet, but it's not much of a hard dependency, so I think it's ok.

Gladish is still GTK2 though, right? I haven't seen any commits that update it to GTK3.

**Comment by maxaudron** [comment]
yes still gtk2

**Comment by simonvanderveldt** [comment]
ok

**Pull request closed without merging**
