### PR TITLE
Carla fixes try #2

### LINKED ISSUE #328: 64-bit media-sound/carla is installing libraries in the wrong places.
Carla is installing the 64-bit libraries in /usr/lib/carla instead of /usr/lib64/carla, and likewise, the pkgconfig in /usr/lib/pkgconfig instead of /usr/lib64/pkgconfig.  While it's not stopping Carla from building and working correctly, it prevents the 64-bit LMMS from detecting Carla (if media-sound/carla is installed) in order to install the carla plugins.

### PR DESCRIPTION
**Pull request by aqxa1**
Okay, hopefully this is correct this time. As before, I've added a workaround to install to the correct libdir, instead of it being hardcoded to /usr/lib, which closes #328. In addition, I've added some changes to respect the [Gentoo Prefix project](https://wiki.gentoo.org/wiki/Project:Prefix). Finally, since you suggested that these changes justify a rev bump, I thought it better to instead bump to Carla 2.1.1 (which I've tested without encountering any obvious issues). Let me know if there are any other issues.

### CODE REVIEW

**Comment by denislobanov** [comment]
It would be awesome to get this merged as `master` doesn't currently build - these changes work for me locally. @aqxa1 do you want me to help out with the merge conflict?

**Comment by simonvanderveldt** [comment]
> It would be awesome to get this merged as `master` doesn't currently build - these changes work for me locally. @aqxa1 do you want any help with this?

@denislobanov Do you mean the live/carla-9999-r1 ebuild doesn't work (so Carla's `master` branch) or that carla-2.0.0-r1.ebuild doesn't work for you? What is the issue?

**Comment by denislobanov** [comment]
@simonvanderveldt Ahh, thank you for the super quick response. For me both ebuilds dont work, current use flags:
```
 * Found these USE flags for media-sound/carla-2.1.1:
 U I
 - - X                              : Add support for X11
 + + alsa                           : Add support for media-libs/alsa-lib (Advanced Linux Sound Architecture)
 - - gtk                            : Add support for x11-libs/gtk+ (The GIMP Toolkit)
 - - gtk2                           : Use gtk-2 instead of gtk-3
 - - opengl                         : Add support for OpenGL (3D graphics)
 - - osc                            : Enable support for Open Sound Control
 - - pulseaudio                     : Add support for PulseAudio sound server
 - - python_single_target_python3_6 : Build for Python 3.6 only
 + + python_single_target_python3_7 : Build for Python 3.7 only
 - - rdf                            : Enable LADSPA-RDF support
 - - sf2                            : Enable builtin SF2 sample support using media-sound/fluidsynth
 - - sndfile                        : Add support for libsndfile
```

emerge output: https://pastebin.com/d1S0XCCr

**Comment by simonvanderveldt** [comment]
@denislobanov Thanks for the info. I'm not sure if you've emerged the version that you've posted the USE flags for but carla-2.1.1 isn't available in this overlay, so I assume you're getting that from somewhere else?

I've just tried emerging both carla-2.0.0-r1 and carla-9999-r1 using `USE=alsa` and python37 and both worked fine. Can you post the failure message you're getting and the first part of the emerge/configure output?

This is what my output for carla-9999-r1 looks like:
```
654c6e010572 /usr/local/portage # USE="alsa" ACCEPT_KEYWORDS="**" emerge -av carla

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R    ] media-sound/carla-9999-r1::audio-overlay  USE="alsa* -X -gtk -gtk2 -opengl -osc -pulseaudio -rdf -sf2 -sndfile" PYTHON_SINGLE_TARGET="python3_7 -python3_6 -python3_8" 0 KiB

Total: 1 package (1 reinstall), Size of downloads: 0 KiB

Would you like to merge these packages? [Yes/No] y

>>> Verifying ebuild manifests

>>> Emerging (1 of 1) media-sound/carla-9999-r1::audio-overlay
 * Using python3.7 to build
>>> Unpacking source...
 * Repository id: falkTX_Carla.git
 * To override fetched repository properties, use:
 *   EGIT_OVERRIDE_REPO_FALKTX_CARLA
 *   EGIT_OVERRIDE_BRANCH_FALKTX_CARLA
 *   EGIT_OVERRIDE_COMMIT_FALKTX_CARLA
 *   EGIT_OVERRIDE_COMMIT_DATE_FALKTX_CARLA
 * 
 * Fetching https://github.com/falkTX/Carla.git ...
git fetch https://github.com/falkTX/Carla.git +HEAD:refs/git-r3/HEAD
git symbolic-ref refs/git-r3/media-sound/carla/0/__main__ refs/git-r3/HEAD
 * Skipping submodule source/native-plugins/external
 * Checking out https://github.com/falkTX/Carla.git to /var/tmp/portage/media-sound/carla-9999-r1/work/carla-9999 ...
git checkout --quiet refs/git-r3/HEAD
GIT update -->
   repository:               https://github.com/falkTX/Carla.git
   at the commit:            8b7203135811064aa7eaae5c1b152398cc81610b
 * Skipping submodule source/native-plugins/external
>>> Source unpacked in /var/tmp/portage/media-sound/carla-9999-r1/work
>>> Preparing source in /var/tmp/portage/media-sound/carla-9999-r1/work/carla-9999 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/media-sound/carla-9999-r1/work/carla-9999 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/media-sound/carla-9999-r1/work/carla-9999 ...
---> Main features 
Front-End:     YES
LV2 plugin:    YES
VST2 plugin:   YES
Link support:  YES
OSC support:   NO  [Missing liblo]
Binary detect: YES

---> Engine drivers 
JACK:        YES
ALSA:        YES
PulseAudio:  NO  [Missing PulseAudio]
CoreAudio:   NO  [MacOS only]
ASIO:        NO  [Windows only]
DirectSound: NO  [Windows only]
WASAPI:      NO  [Windows only]

---> Plugin formats: 
Internal: YES
LADSPA:   YES
DSSI:     YES
LV2:      YES
VST2:     YES (without UI) [Missing X11]
VST3:     NO
AU:       NO  [MacOS only]

---> LV2 UI toolkit support: 
External: YES (direct)
Gtk2:     NO  [Gtk2 missing]
Gtk3:     NO  [Gtk3 missing]
Qt4:      NO  [Qt4 missing]
Qt5:      YES (bridge)
X11:      NO  [X11 missing]
Cocoa:    NO  [MacOS only]
Windows:  NO  [Windows only]

---> File formats: 
Basic: NO [libsndfile missing]
Extra: NO [FFmpeg missing or too new]
SF2/3: NO [FluidSynth missing or too old]
SFZ:   YES

---> Internal plugins: 
Basic Plugins:    YES
Carla-Patchbay:   YES
Carla-Rack:       YES
External Plugins: NO
```

P.S. It's probably better to create a separate issue for this since it doesn't really have to do with this PR

**Comment by simonvanderveldt** [comment]
@denislobanov FYI we've justed bumped the carla version to 2.2.0 and included a fix for the libdir. This is working fine for me and the emerge passed without issues on our CI.
If you still run into problems feel free to create an issue so we can look at it.

**Pull request closed without merging**
