### PR TITLE
media-sound/bitwig-studio: Bump to 4.0.4

### PR DESCRIPTION
**Pull request by KevinThomas0**
It looks like the issue in 4.0.1 (https://github.com/gentoo-audio/audio-overlay/issues/474) is gone now, however a different issue came up that seemed to have to do with file permissions. I updated the ebuild to fix these, and now everything is working for me.

### CODE REVIEW

**Comment by KevinThomas0** [comment]
Also if you want to, I'd appreciate it if you could add the `hacktoberfest-accepted` label to this PR if it looks good, I'm trying to participate in [hacktoberfest](https://hacktoberfest.digitalocean.com/) this year!

**Review by simonvanderveldt — APPROVED** [review]
Thanks!

Sorry, I don't have time to look at this, but will approve/merge it assuming you've tested it/that it works for you.
Do you maybe want to join so you can maintain the package directly yourself?

**Comment by KevinThomas0** [comment]
@simonvanderveldt Thank you! And yes, that would be great!

**Comment by KevinThomas0** [comment]
> Do you maybe want to join so you can maintain the package directly yourself?

Sorry, forgot to reply to this part, I would definitely be willing to do this and maintain the package!

**Pull request merged**
