### PR TITLE
github-page: add theme configuration

### PR DESCRIPTION
**Pull request by mrVanDalo**
This will https://gentoo-audio.github.io/audio-overlay/  a proper style

### CODE REVIEW

**Comment by simonvanderveldt** [comment]
> This will https://gentoo-audio.github.io/audio-overlay/ a proper style

I actually quiet like how simple and clean this looks :x

Which theme is this exactly/what does it look like?
Is it the one where there's a lot of unused space to the left with just a title or sth like that on the left?

Also, what do you want to use it for? Adding docs or just so the readme can be styled?

**Comment by mrVanDalo** [comment]
Well this is just the first step, I would like to have something like the wiki of proaudio, containing some information about some special packages and stuff

**Comment by simonvanderveldt** [comment]
Hmm, I'm not sure. The simple theme adds buttons to the page that are useless to our users (download a ZIP file of the overlay :x) See example screenshot
image

Right now it's just the instructions which makes a lot more sense.

Also, I don't know how wiki like you want it to be, but I found it quiet difficult to setup a decent wiki-like thing using github pages. This is what I ended up with, though I'm still not 100% happy with it. http://rennsportengineering.com/wiki/. Code lives here https://github.com/rennsportengineering/wiki

Maybe GitHub's integrated wiki that's part of this repo is good enough?
Why not use gentoo's wiki btw?

**Comment by mrVanDalo** [comment]
There will be no zip download unless we create releases. And of course we could use a wiki we have to install somewhere with a WYSIWYG-Editor, but github pages are very easy to maintain, and the have a very nice look and they will follow the pull-request rule-set we just implemented.

This is a simple change with a lot of effect. Everything more complicated can follow.

Of course you can pick another theme, but I'm in the simple stuff.
https://github.com/blog/1081-instantly-beautiful-project-pages

There are of course themes out there which need to be integrated, but it's not that complicated though
https://github.com/jekyll/jekyll/wiki/Themes

**Comment by marcan** [comment]
Is there a way to preview this, preferably without locally installing a bunch of jekyll stuff?

**Comment by mrVanDalo** [comment]
@marcan : simonvanderveldt just posted a screenshot on how this would look like

**Comment by simonvanderveldt** [comment]
> Is there a way to preview this, preferably without locally installing a bunch of jekyll stuff?

@marcan I build/serve it using Jekyll's Docker image. There's a github pages specific tag for it `jekyll/jekyll:pages`

**Comment by mrVanDalo** [comment]
I just created a new repo for the github page of the organization, https://gentoo-audio.github.io/
It contains just the readme for now, but I'll put a jekyll project in there soon.

**Pull request closed without merging**
